#! /usr/bin/env bash

# This is intended to help automate the process of pull changes down from
# ruby-build upstream. It uses custom 'rbtags' ref namespace for ruby-build's
# tags (that way ruby-builds tags don't pollute node-build's tags). It re-uses
# a staging branch where ruby-build's tags will be merged into. It finds only
# the very "next" un-merged ruby-build tag; diffs against that and merges it.
# Then removes the ruby-build defs and known scripts that don't apply to
# node-build. Should leave the working copy in a MERGING state.

set -euo pipefail

confirm() { read -rp "Press Enter to continue or Ctrl-C to quit"; }
fail() { echo "Aborting: ${1-$(cat -)}" >&2; false; }
trace() { (set -x; "$@"); }
usage() { sed -ne "/^#/ !q; s/^#$/# /; /^# / { s/^# //; p; }"; }

rbtags='refs/rbtags/'
ruby_build='https://github.com/rbenv/ruby-build.git'
branch='pull-ruby-build'

fetch_rbtags() {
  git fetch --no-tags $ruby_build "refs/tags/*:$rbtags*"
}

clean_branch() {
  git diff --stat --exit-code HEAD || fail "Unclean working directory"

  [ "$branch" = "$(git rev-parse --abbrev-ref HEAD)" ] ||
  git checkout --no-track -b "$branch" 'origin/main'
}

rbtag(){
  merged=$1
  main=${2:-HEAD}
  case $merged in
  --merged) only='tail' ;;
  --no-merged) only='head' ;;
  *) exit 1 ;;
  esac

  trace git for-each-ref $rbtags \
  --format '%(refname)' --sort=refname "$merged" "$main" | $only -1
}

next_unmerged_rbtag(){
  {
    upstream=${1:-ruby-build/master}
    main=${2:-HEAD}

    trace git describe --all --exact-match \
      "$(trace git merge-base "$main" "$upstream")"

    vlast=$(rbtag --merged)
    vnext=$(rbtag --no-merged)

    trace git diff "${vlast:?}"..."${vnext:?}" \
      -- ':!share/' ':!script/*ruby*'
  } >&2

  echo "$vnext"
}

merge(){
  ref=${1:?}

  # FIXME: find better way to handle the expected errexit
  # TODO: improve commit message
  git merge --no-commit --quiet "$ref" || true

  # TODO: this stuff should be a custom merge-driver
  git rm -rf share/ruby-build
  git rm -rf script/update-*ruby
}

fetch_rbtags
clean_branch

merge "$(next_unmerged_rbtag ruby-build/master)"
