#!/bin/bash
# Usage: script/release
#
# preversion
# - fetchs from origin
# - ensures it isn't already tagged
# - ensures currently on master branch
# - ensures there are bin or definition changes to release
# version (handled by npm)
# - bumps version in package.json
# - commits and tags
# postversion
# - pushes master + tag to GitHub
# - opens pull request to update the Homebrew formula
#
# TODO: publish release notes to GitHub

set -e

new_tag="v${npm_package_version}"

preversion() {
  git fetch -q --tags origin master

  local existing="$(git tag --points-at HEAD)"
  if [ -n "$existing" ]; then
    echo "Aborting: HEAD is already tagged as '${existing}'" >&2
    exit 1
  fi

  local current_branch="$(git symbolic-ref --short HEAD)"
  if [ "$current_branch" != master ]; then
    echo "Aborting: Not currently on master branch" >&2
    exit 1
  fi

  previous_tag="$(git describe --tags --abbrev=0)"
  if git diff --quiet "${previous_tag}..HEAD" -- bin share; then
    echo "Aborting: No features to release since '${previous_tag}'" >&2
    exit 1
  fi
}

postversion() {
  git push origin master "${new_tag}"

  script/brew-publish node-build "$new_tag"
}


cmd="$1"

case "$cmd" in
  preversion | postversion )
    shift 1
    "$cmd" "$@"
    ;;
  * )
    echo "should be invoked via npm-version" >&2
    exit 1
    ;;
esac
